### ISSUE TITLE
Fix vulnerable dependencies in package-lock.json

### ISSUE THREAD

**Issue by chetanraj** [chetanraj/my-investments#1]
There are three dependencies in the `package-lock.json` file which have vulnurabilities:

- twbs / bootstrap
- scravy / node-macaddress

Need to upgrade the versions in package-lock.json or upgrade the dependencies that reference those dependencies in package.json.

**Comment by kmjayadeep** [comment]
Can i take this up?

**Comment by chetanraj** [comment]
@kmjayadeep - yes you can.

**Comment by kmjayadeep** [comment]
I'm on it
